name: openssl_bindings
version: 1.0.0
description: FFI bindings to OpenSSL cryptographic library for Dart, providing native access to encryption, hashing, and SSL/TLS functionality.

environment:
  sdk: '^3.6.0'

dependencies:
  ffi: ^2.1.2
  logging: ^1.3.0
  #meta: ^1.15.0
 

  meta: any
dev_dependencies:   
  hex: ^0.2.0
  test: ^1.26.3  
  ffigen: ^19.0.0

 